### ISSUE TITLE
A way to animate to a new value without restarting animation?

### ISSUE THREAD

**Issue by deucks** [knn90/KNCirclePercentView#4]
Great implementation! But from the example i see that when entering a new percentage it seems to reanimate the whole progress bar. Is there any way to just animate upto the updated value?

**Comment by knn90** [comment]
Do you mean this:
1. Draw to 50% with red
2. Draw from 50% to 70% with green
and so on..

**Comment by deucks** [comment]
yeah something like that would good

**Comment by knn90** [comment]
I will modify my code and create some demo. May be next week

**Comment by deucks** [comment]
ok thanks!

**Comment by knn90** [comment]
I implemented another demo for you. Check out this https://github.com/knn90/KNPieChart. If you have any comment, don't hesitate to let me know. Hope this help you somehow :)
